title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
github:
  is_project_page: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman
